
let skill = [
    { name: "HTML5", imgSrc: "https://skillicons.dev/icons?i=html" },
    { name: "CSS3", imgSrc: "https://skillicons.dev/icons?i=css" },
    { name: "less", imgSrc: "https://skillicons.dev/icons?i=less" },
    { name: "sass", imgSrc: "https://skillicons.dev/icons?i=sass" },
    { name: "JavaScript", imgSrc: "https://skillicons.dev/icons?i=js" },
    { name: "TypeScript", imgSrc: "https://skillicons.dev/icons?i=ts" },
    { name: "Node", imgSrc: "https://skillicons.dev/icons?i=nodejs" },
    { name: "Bun", imgSrc: "https://skillicons.dev/icons?i=bun" },
    { name: "Vue", imgSrc: "https://skillicons.dev/icons?i=vue" },
    { name: "jquery", imgSrc: "https://skillicons.dev/icons?i=jquery" },
    { name: "Vite", imgSrc: "https://skillicons.dev/icons?i=vite" },
    { name: "Webpack", imgSrc: "https://skillicons.dev/icons?i=webpack" },
    { name: "VitePress", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=vitepress" },
    { name: "Electron", imgSrc: "https://skillicons.dev/icons?i=electron" },
    { name: "Java", imgSrc: "https://skillicons.dev/icons?i=java" },
    { name: "Rust", imgSrc: "https://skillicons.dev/icons?i=rust" },
    { name: "Tauri", imgSrc: "https://skillicons.dev/icons?i=tauri" },
    { name: "c#", imgSrc: "https://skillicons.dev/icons?i=cs" },
    { name: "docker", imgSrc: "https://skillicons.dev/icons?i=docker" },
    { name: "neovim", imgSrc: "https://skillicons.dev/icons?i=neovim" },
    { name: "git", imgSrc: "https://skillicons.dev/icons?i=git" },
    { name: "github", imgSrc: "https://skillicons.dev/icons?i=github" },
    { name: "linux", imgSrc: "https://skillicons.dev/icons?i=linux" },
    { name: "windows", imgSrc: "https://skillicons.dev/icons?i=windows" },
    { name: "gradle", imgSrc: "https://skillicons.dev/icons?i=gradle" },
    { name: "maven", imgSrc: "https://skillicons.dev/icons?i=maven" },
    { name: "jenkins", imgSrc: "https://skillicons.dev/icons?i=jenkins" },
    { name: "kubernetes", imgSrc: "https://skillicons.dev/icons?i=kubernetes" },
    { name: "nginx", imgSrc: "https://skillicons.dev/icons?i=nginx" },
    { name: "mongodb", imgSrc: "https://skillicons.dev/icons?i=mongodb" },
    { name: "mysql", imgSrc: "https://skillicons.dev/icons?i=mysql" },
    { name: "postgresql", imgSrc: "https://skillicons.dev/icons?i=postgresql" },
    { name: "redis", imgSrc: "https://skillicons.dev/icons?i=redis" },
    { name: "latex", imgSrc: "https://skillicons.dev/icons?i=latex" },
    { name: "markdown", imgSrc: "https://skillicons.dev/icons?i=md" },
    { name: "lua", imgSrc: "https://skillicons.dev/icons?i=lua" },
    { name: "python", imgSrc: "https://skillicons.dev/icons?i=python" },
    { name: "go", imgSrc: "https://skillicons.dev/icons?i=go" },
    { name: "c", imgSrc: "https://skillicons.dev/icons?i=c" },
    { name: "cpp", imgSrc: "https://skillicons.dev/icons?i=cpp" },
    { name: "npm", imgSrc: "https://skillicons.dev/icons?i=npm" },
    { name: "yarn", imgSrc: "https://skillicons.dev/icons?i=yarn" },
    { name: "pnpm", imgSrc: "https://skillicons.dev/icons?i=pnpm" },
    { name: "bash", imgSrc: "https://skillicons.dev/icons?i=bash" },
    { name: "pinia", imgSrc: "https://skillicons.dev/icons?i=pinia" },
    { name: "pug", imgSrc: "https://skillicons.dev/icons?i=pug" },
    { name: "spring", imgSrc: "https://skillicons.dev/icons?i=spring" },
    { name: "sqlite", imgSrc: "https://skillicons.dev/icons?i=sqlite" },
    { name: "swift", imgSrc: "https://skillicons.dev/icons?i=swift" },
    { name: "tailwind", imgSrc: "https://skillicons.dev/icons?i=tailwind" },
    { name: "threejs", imgSrc: "https://skillicons.dev/icons?i=threejs" },
    { name: "wasm", imgSrc: "https://skillicons.dev/icons?i=wasm" },
    { name: "zshell", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=zshell" },
    { name: "tailwindcss", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=tailwindcss" },
    { name: "springboot", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=springboot" },
    { name: "springcloud", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=springcloud" },
    { name: "stackoverflow", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=stackoverflow" },
    { name: "elementplus", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=elementplus" },
    { name: "elasticsearch", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=elasticsearch" },
    { name: "babel", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=babel" },
    { name: "eslint", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=eslint" },
    { name: "prettier", imgSrc: "https://skills.syvixor.com/api/icons?perline=15&i=prettier" }
]
export default {
    myTag: ["喜欢折腾新技术的前端人", "热爱编程的码农", "游戏 mod 开发者", "热爱生活的普通人", "未来的小说家", "业余摄影师", "电影爱好者", "音乐发烧友"],
    myLearnedSkill: skill
}
export type Skill = { name: string, imgSrc: string }[]