export default {
    ignoreFile: [
        'code',
        '\\.DS_Store',
        'image',
        'img',
        'examples',
        'assert',
        'css',
        'node_modules',
        '.*\\.json',
        '.*\\.env',
        'file',
        '.*\\.yaml',
        '.*\\.txt',
        '.*\\.ts',
    ],
    baseUrl: 'http://localhost:5173',
    steamUrl: 'https://steamcommunity.com/profiles/76561198841892559/',
}
